// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.MVVM {
    using Invert.Core.GraphDesigner;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class SubSystemNodeDrawerBase : GenericNodeDrawer<SubSystemNode,SubSystemNodeViewModel> {
        
        public SubSystemNodeDrawerBase(SubSystemNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SceneTypeNodeDrawerBase : GenericNodeDrawer<SceneTypeNode,SceneTypeNodeViewModel> {
        
        public SceneTypeNodeDrawerBase(SceneTypeNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class MVVMNodeDrawerBase : GenericNodeDrawer<MVVMNode,MVVMNodeViewModel> {
        
        public MVVMNodeDrawerBase(MVVMNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
}
