// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.MVVM {
    using Invert.Core.GraphDesigner;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class ServiceNodeDrawerBase : GenericNodeDrawer<ServiceNode,ServiceNodeViewModel> {
        
        public ServiceNodeDrawerBase(ServiceNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SimpleClassNodeDrawerBase : GenericNodeDrawer<SimpleClassNode,SimpleClassNodeViewModel> {
        
        public SimpleClassNodeDrawerBase(SimpleClassNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SubSystemNodeDrawerBase : GenericNodeDrawer<SubSystemNode,SubSystemNodeViewModel> {
        
        public SubSystemNodeDrawerBase(SubSystemNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SceneTypeNodeDrawerBase : GenericNodeDrawer<SceneTypeNode,SceneTypeNodeViewModel> {
        
        public SceneTypeNodeDrawerBase(SceneTypeNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ElementNodeDrawerBase : GenericNodeDrawer<ElementNode,ElementNodeViewModel> {
        
        public ElementNodeDrawerBase(ElementNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class CommandNodeDrawerBase : GenericNodeDrawer<CommandNode,CommandNodeViewModel> {
        
        public CommandNodeDrawerBase(CommandNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class MVVMNodeDrawerBase : GenericNodeDrawer<MVVMNode,MVVMNodeViewModel> {
        
        public MVVMNodeDrawerBase(MVVMNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
}
