// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using uFrame.Editor.Graphs.Data;

namespace uFrame.MVVM {
    
    public class SubSystemGraphBase : GenericGraphData<SubSystemNode> {
    }
    
    public class MVVMGraphBase : GenericGraphData<MVVMNode> {
    }
}
