// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using uFrame.Editor.Configurations;
using uFrame.Editor.Core;
using uFrame.Editor.Graphs.Data;

namespace uFrame.MVVM {
    using System;
    using System.Linq;
    
    
    public class ServiceNodeBase : GenericInheritableNode, IClassTypeNode {
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<IItem> PossibleHandlers {
            get {
                return this.Repository.AllOf<IHandlersConnectable>().Cast<IItem>();
            }
        }
        
        [ReferenceSection("Handlers", SectionVisibility.Always, false, false, typeof(IHandlersConnectable), false, OrderIndex=0, HasPredefinedOptions=false, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<HandlersReference> Handlers {
            get {
                return PersistedItems.OfType<HandlersReference>();
            }
        }
    }
    
    public partial interface IServiceConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class SimpleClassNodeBase : GenericInheritableNode, IClassTypeNode {
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        [Section("Properties", SectionVisibility.Always, OrderIndex=1, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<PropertiesChildItem> Properties {
            get {
                return PersistedItems.OfType<PropertiesChildItem>();
            }
        }
        
        [Section("Collections", SectionVisibility.Always, OrderIndex=2, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CollectionsChildItem> Collections {
            get {
                return PersistedItems.OfType<CollectionsChildItem>();
            }
        }
    }
    
    public partial interface ISimpleClassConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class SubSystemNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<IItem> PossibleInstances {
            get {
                return this.Repository.AllOf<IInstancesConnectable>().Cast<IItem>();
            }
        }
        
        [ReferenceSection("Instances", SectionVisibility.Always, false, false, typeof(IInstancesConnectable), false, OrderIndex=0, HasPredefinedOptions=false, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<InstancesReference> Instances {
            get {
                return PersistedItems.OfType<InstancesReference>();
            }
        }
    }
    
    public partial interface ISubSystemConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ViewNodeBase : GenericInheritableNode, IClassTypeNode {
        
        private string _ElementInputSlotId;
        
        private string _ScenePropertiesInputSlotId;
        
        private Element _Element;
        
        private SceneProperties _SceneProperties;
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<IItem> PossibleBindings {
            get {
                return this.Repository.AllOf<IBindingsConnectable>().Cast<IItem>();
            }
        }
        
        [ReferenceSection("Bindings", SectionVisibility.Always, false, false, typeof(IBindingsConnectable), false, OrderIndex=3, HasPredefinedOptions=false, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<BindingsReference> Bindings {
            get {
                return PersistedItems.OfType<BindingsReference>();
            }
        }
        
        [Json.JsonProperty()]
        public virtual string ElementInputSlotId {
            get {
                if (_ElementInputSlotId == null) {
                    _ElementInputSlotId = Guid.NewGuid().ToString();
                }
                return _ElementInputSlotId;
            }
            set {
                _ElementInputSlotId = value;
            }
        }
        
        [Json.JsonProperty()]
        public virtual string ScenePropertiesInputSlotId {
            get {
                if (_ScenePropertiesInputSlotId == null) {
                    _ScenePropertiesInputSlotId = Guid.NewGuid().ToString();
                }
                return _ScenePropertiesInputSlotId;
            }
            set {
                _ScenePropertiesInputSlotId = value;
            }
        }
        
        [InputSlot("Element", false, SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual Element ElementInputSlot {
            get {
                if (Repository == null) {
                    return null;
                }
                if (_Element != null) {
                    return _Element;
                }
                return _Element ?? (_Element = new Element() { Repository = Repository, Node = this, Identifier = ElementInputSlotId });
            }
        }
        
        [InputSlot("Scene Properties", true, SectionVisibility.Always, OrderIndex=1, IsNewRow=true)]
        public virtual SceneProperties ScenePropertiesInputSlot {
            get {
                if (Repository == null) {
                    return null;
                }
                if (_SceneProperties != null) {
                    return _SceneProperties;
                }
                return _SceneProperties ?? (_SceneProperties = new SceneProperties() { Repository = Repository, Node = this, Identifier = ScenePropertiesInputSlotId });
            }
        }
    }
    
    public partial interface IViewConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class SceneTypeNodeBase : GenericInheritableNode, IClassTypeNode {
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ISceneTypeConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ElementNodeBase : GenericInheritableNode, IClassTypeNode, IElementConnectable {
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        [Section("Commands", SectionVisibility.Always, OrderIndex=3, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CommandsChildItem> Commands {
            get {
                return PersistedItems.OfType<CommandsChildItem>();
            }
        }
        
        [Section("Collections", SectionVisibility.Always, OrderIndex=2, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CollectionsChildItem> Collections {
            get {
                return PersistedItems.OfType<CollectionsChildItem>();
            }
        }
        
        [Section("Properties", SectionVisibility.Always, OrderIndex=1, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<PropertiesChildItem> Properties {
            get {
                return PersistedItems.OfType<PropertiesChildItem>();
            }
        }
    }
    
    public partial interface IElementConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class CommandNodeBase : GenericInheritableNode, IClassTypeNode {
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        [Section("Properties", SectionVisibility.Always, OrderIndex=1, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<PropertiesChildItem> Properties {
            get {
                return PersistedItems.OfType<PropertiesChildItem>();
            }
        }
        
        [Section("Collections", SectionVisibility.Always, OrderIndex=2, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CollectionsChildItem> Collections {
            get {
                return PersistedItems.OfType<CollectionsChildItem>();
            }
        }
    }
    
    public partial interface ICommandConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class MVVMNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IMVVMConnectable : IDiagramNodeItem, IConnectable {
    }
}
