// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace uFrame.MVVM {
    using Invert.Core;
    using Invert.Core.GraphDesigner;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class uFrameMVVMBase : Invert.Core.GraphDesigner.DiagramPlugin {
        
        private Invert.Core.GraphDesigner.NodeConfig<ServiceNode> _Service;
        
        private Invert.Core.GraphDesigner.NodeConfig<SimpleClassNode> _SimpleClass;
        
        private Invert.Core.GraphDesigner.NodeConfig<SubSystemNode> _SubSystem;
        
        private Invert.Core.GraphDesigner.NodeConfig<ViewNode> _View;
        
        private Invert.Core.GraphDesigner.NodeConfig<SceneTypeNode> _SceneType;
        
        private Invert.Core.GraphDesigner.NodeConfig<ElementNode> _Element;
        
        private Invert.Core.GraphDesigner.NodeConfig<CommandNode> _Command;
        
        private Invert.Core.GraphDesigner.NodeConfig<MVVMNode> _MVVM;
        
        public Invert.Core.GraphDesigner.NodeConfig<ServiceNode> Service {
            get {
                return _Service;
            }
            set {
                _Service = value;
            }
        }
        
        public Invert.Core.GraphDesigner.NodeConfig<SimpleClassNode> SimpleClass {
            get {
                return _SimpleClass;
            }
            set {
                _SimpleClass = value;
            }
        }
        
        public Invert.Core.GraphDesigner.NodeConfig<SubSystemNode> SubSystem {
            get {
                return _SubSystem;
            }
            set {
                _SubSystem = value;
            }
        }
        
        public Invert.Core.GraphDesigner.NodeConfig<ViewNode> View {
            get {
                return _View;
            }
            set {
                _View = value;
            }
        }
        
        public Invert.Core.GraphDesigner.NodeConfig<SceneTypeNode> SceneType {
            get {
                return _SceneType;
            }
            set {
                _SceneType = value;
            }
        }
        
        public Invert.Core.GraphDesigner.NodeConfig<ElementNode> Element {
            get {
                return _Element;
            }
            set {
                _Element = value;
            }
        }
        
        public Invert.Core.GraphDesigner.NodeConfig<CommandNode> Command {
            get {
                return _Command;
            }
            set {
                _Command = value;
            }
        }
        
        public Invert.Core.GraphDesigner.NodeConfig<MVVMNode> MVVM {
            get {
                return _MVVM;
            }
            set {
                _MVVM = value;
            }
        }
        
        public virtual Invert.Core.GraphDesigner.SelectTypeCommand GetPropertiesSelectionCommand() {
            return new SelectTypeCommand() { IncludePrimitives = true, AllowNone = false };
        }
        
        public virtual Invert.Core.GraphDesigner.SelectTypeCommand GetCollectionsSelectionCommand() {
            return new SelectTypeCommand() { IncludePrimitives = true, AllowNone = false };
        }
        
        public virtual Invert.Core.GraphDesigner.SelectTypeCommand GetCommandsSelectionCommand() {
            return new SelectTypeCommand() { IncludePrimitives = true, AllowNone = false };
        }
        
        public override void Initialize(Invert.IOC.UFrameContainer container) {
            container.AddTypeItem<CommandsChildItem>();
            container.AddItem<HandlersReference>();
            container.AddTypeItem<PropertiesChildItem>();
            container.AddItem<InstancesReference>();
            container.AddTypeItem<CollectionsChildItem>();
            Service = container.AddNode<ServiceNode,ServiceNodeViewModel,ServiceNodeDrawer>("Service");
            Service.Inheritable();
            Service.Color(NodeColor.LightGray);
            Service.HasSubNode<SimpleClassNode>();
            SimpleClass = container.AddNode<SimpleClassNode,SimpleClassNodeViewModel,SimpleClassNodeDrawer>("SimpleClass");
            SimpleClass.Inheritable();
            SimpleClass.Color(NodeColor.Gray);
            SubSystem = container.AddGraph<SubSystemGraph, SubSystemNode>("SubSystemGraph");
            SubSystem.Color(NodeColor.Blue);
            SubSystem.HasSubNode<ServiceNode>();
            SubSystem.HasSubNode<SimpleClassNode>();
            SubSystem.HasSubNode<ElementNode>();
            SubSystem.HasSubNode<CommandNode>();
            View = container.AddNode<ViewNode,ViewNodeViewModel,ViewNodeDrawer>("View");
            View.Inheritable();
            View.Color(NodeColor.Royalblue2);
            SceneType = container.AddNode<SceneTypeNode,SceneTypeNodeViewModel,SceneTypeNodeDrawer>("SceneType");
            SceneType.Inheritable();
            SceneType.Color(NodeColor.Orange);
            Element = container.AddNode<ElementNode,ElementNodeViewModel,ElementNodeDrawer>("Element");
            Element.Inheritable();
            Element.Color(NodeColor.Yellow);
            Element.HasSubNode<SimpleClassNode>();
            Element.HasSubNode<ViewNode>();
            Element.HasSubNode<CommandNode>();
            Command = container.AddNode<CommandNode,CommandNodeViewModel,CommandNodeDrawer>("Command");
            Command.Inheritable();
            Command.Color(NodeColor.Red);
            MVVM = container.AddGraph<MVVMGraph, MVVMNode>("MVVMGraph");
            MVVM.Color(NodeColor.DarkGray);
            MVVM.HasSubNode<SimpleClassNode>();
            MVVM.HasSubNode<SubSystemNode>();
            MVVM.HasSubNode<SceneTypeNode>();
            MVVM.HasSubNode<ServiceNode>();
            container.Connectable<ElementNode,Element>();
            container.Connectable<HandlersReference,SimpleClassNode>();
        }
    }
}
