// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using uFrame.Editor.Graphs.Data;

namespace uFrame.MVVM {
    
    
    public class HandlersReferenceBase : GenericReferenceItem<IHandlersConnectable>, ISimpleClassConnectable {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IHandlersConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class InstancesReferenceBase : GenericReferenceItem<IInstancesConnectable> {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IInstancesConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class BindingsReferenceBase : GenericReferenceItem<IBindingsConnectable> {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IBindingsConnectable : IDiagramNodeItem, IConnectable {
    }
}
