// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using uFrame.Editor.Database.Data;
using uFrame.Editor.Graphs.Data;

namespace uFrame.MVVM {
    using System.Linq;
    
    
    public class ElementBase : SingleInputSlot<IElementConnectable> {
        
        public override string Name {
            get {
                return "Element";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return false;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<IValueItem> GetAllowed() {
            return Repository.AllOf<IElementConnectable>().OfType<IValueItem>();;
        }
    }
    
    public partial interface IElementConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ScenePropertiesBase : MultiInputSlot<IScenePropertiesConnectable> {
        
        public override string Name {
            get {
                return "Scene Properties";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<IValueItem> GetAllowed() {
            return Repository.AllOf<IScenePropertiesConnectable>().OfType<IValueItem>();;
        }
    }
    
    public partial interface IScenePropertiesConnectable : IDiagramNodeItem, IConnectable {
    }
}
