// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.MVVM {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class SubSystemNodeViewModelBase : Invert.Core.GraphDesigner.GenericNodeViewModel<Invert.Core.GraphDesigner.GenericNode> {
        
        public SubSystemNodeViewModelBase(SubSystemNode graphItemObject, Invert.Core.GraphDesigner.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override Invert.Core.GraphDesigner.NodeStyle NodeStyle {
            get {
                return Invert.Core.GraphDesigner.NodeStyle.Minimalistic;
            }
        }
    }
    
    public class SceneTypeNodeViewModelBase : Invert.Core.GraphDesigner.GenericNodeViewModel<Invert.Core.GraphDesigner.GenericNode> {
        
        public SceneTypeNodeViewModelBase(SceneTypeNode graphItemObject, Invert.Core.GraphDesigner.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override Invert.Core.GraphDesigner.NodeStyle NodeStyle {
            get {
                return Invert.Core.GraphDesigner.NodeStyle.Normal;
            }
        }
    }
    
    public class MVVMNodeViewModelBase : Invert.Core.GraphDesigner.GenericNodeViewModel<Invert.Core.GraphDesigner.GenericNode> {
        
        public MVVMNodeViewModelBase(MVVMNode graphItemObject, Invert.Core.GraphDesigner.DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override Invert.Core.GraphDesigner.NodeStyle NodeStyle {
            get {
                return Invert.Core.GraphDesigner.NodeStyle.Normal;
            }
        }
    }
}
