// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using uFrame.Editor.Graphs.Data;
using uFrame.Editor.GraphUI.ViewModels;
using uFrame.Editor.Platform;

namespace uFrame.MVVM {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class ServiceNodeViewModelBase : GenericNodeViewModel<GenericNode> {
        
        public ServiceNodeViewModelBase(ServiceNode graphItemObject, DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class SimpleClassNodeViewModelBase : GenericNodeViewModel<GenericNode> {
        
        public SimpleClassNodeViewModelBase(SimpleClassNode graphItemObject, DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class SubSystemNodeViewModelBase : GenericNodeViewModel<GenericNode> {
        
        public SubSystemNodeViewModelBase(SubSystemNode graphItemObject, DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override NodeStyle NodeStyle {
            get {
                return NodeStyle.Minimalistic;
            }
        }
    }
    
    public class ViewNodeViewModelBase : GenericNodeViewModel<GenericNode> {
        
        public ViewNodeViewModelBase(ViewNode graphItemObject, DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class SceneTypeNodeViewModelBase : GenericNodeViewModel<GenericNode> {
        
        public SceneTypeNodeViewModelBase(SceneTypeNode graphItemObject, DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class ElementNodeViewModelBase : GenericNodeViewModel<GenericNode> {
        
        public ElementNodeViewModelBase(ElementNode graphItemObject, DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class CommandNodeViewModelBase : GenericNodeViewModel<GenericNode> {
        
        public CommandNodeViewModelBase(CommandNode graphItemObject, DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
    
    public class MVVMNodeViewModelBase : GenericNodeViewModel<GenericNode> {
        
        public MVVMNodeViewModelBase(MVVMNode graphItemObject, DiagramViewModel diagramViewModel) : 
                base(graphItemObject, diagramViewModel) {
        }
        
        public override NodeStyle NodeStyle {
            get {
                return NodeStyle.Normal;
            }
        }
    }
}
