// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using uFrame.Editor.Configurations;
using uFrame.Editor.Core;

namespace uFrame.ECS.Editor
{
    using ChildItems;
    using Nodes;
    using Sections;
    using Slots;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Editor.Graphs.Data;

    public class CustomActionNodeBase : SequenceContainerNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        [Section("Outputs", SectionVisibility.WhenNodeIsNotFilter, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<OutputsChildItem> Outputs {
            get {
                return PersistedItems.OfType<OutputsChildItem>();
            }
        }
        
        [Section("Inputs", SectionVisibility.WhenNodeIsNotFilter, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<InputsChildItem> Inputs {
            get {
                return PersistedItems.OfType<InputsChildItem>();
            }
        }
        
        [Section("Branches", SectionVisibility.WhenNodeIsNotFilter, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<BranchesChildItem> Branches {
            get {
                return PersistedItems.OfType<BranchesChildItem>();
            }
        }
    }
    
    public partial interface ICustomActionConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class DataNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IDataConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class LibraryNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ILibraryConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class NullNodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface INullConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class StringLiteralNodeBase : VariableNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IStringLiteralConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class PropertyNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IPropertyConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class StringNodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IStringConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ActionGroupNodeBase : SequenceItemNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IActionGroupConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class StopTimerNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IStopTimerConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class FunctionNodeBase : SequenceItemNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IFunctionConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class BoolNodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IBoolConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ModuleNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IModuleConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class AnyFalseNodeBase : BoolExpressionNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IAnyFalseConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class CodeActionNodeBase : ActionNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ICodeActionConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class BoolExpressionNodeBase : GenericNode, IExpressionsConnectable, IGroupConnectable {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IBoolExpressionConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class FloatNodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IFloatConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class UserMethodNodeBase : SequenceItemNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IUserMethodConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class LoopCollectionNodeBase : SequenceItemNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ILoopCollectionConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ComponentCreatedNodeBase : HandlerNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IComponentCreatedConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class SetVariableNodeBase : SequenceItemNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ISetVariableConnectable : IDiagramNodeItem, IConnectable {
    }

    public class AnyTrueNodeBase : BoolExpressionNode
    {

        private string _ExpressionsInputSlotId;

        private Expressions _Expressions;

        public override bool AllowMultipleInputs
        {
            get
            {
                return true;
            }
        }

        public override bool AllowMultipleOutputs
        {
            get
            {
                return true;
            }
        }

        [Json.JsonProperty()]
        public virtual string ExpressionsInputSlotId
        {
            get
            {
                if (_ExpressionsInputSlotId == null)
                {
                    _ExpressionsInputSlotId = Guid.NewGuid().ToString();
                }
                return _ExpressionsInputSlotId;
            }
            set
            {
                _ExpressionsInputSlotId = value;
            }
        }

        [InputSlot("Expressions", true, SectionVisibility.Always, OrderIndex = 0, IsNewRow = true)]
        public virtual Expressions ExpressionsInputSlot
        {
            get
            {
                if (Repository == null)
                {
                    return null;
                }
                if (_Expressions != null)
                {
                    return _Expressions;
                }
                return _Expressions ?? (_Expressions = new Expressions() { Repository = Repository, Node = this, Identifier = ExpressionsInputSlotId });
            }
        }
    }

    public partial interface IAnyTrueConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class CollectionItemRemovedNodeBase : CollectionModifiedHandlerNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ICollectionItemRemovedConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class CollectionModifiedHandlerNodeBase : HandlerNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ICollectionModifiedHandlerConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ObjectNodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IObjectConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class PropertyChangedNodeBase : HandlerNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IPropertyChangedConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class VariableNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IVariableConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class GroupNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<IItem> PossibleRequire {
            get {
                return this.Repository.AllOf<IRequireConnectable>().Cast<IItem>();
            }
        }
        
        [ReferenceSection("Require", SectionVisibility.Always, false, false, typeof(IRequireConnectable), false, OrderIndex=0, HasPredefinedOptions=false, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<RequireReference> Require {
            get {
                return PersistedItems.OfType<RequireReference>();
            }
        }
    }
    
    public partial interface IGroupConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class DescriptorNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IDescriptorConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class Vector3NodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IVector3Connectable : IDiagramNodeItem, IConnectable {
    }
    
    public class EventNodeBase : GenericInheritableNode, IClassTypeNode {
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        [Section("Properties", SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<PropertiesChildItem> Properties {
            get {
                return PersistedItems.OfType<PropertiesChildItem>();
            }
        }
        
        [Section("Collections", SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CollectionsChildItem> Collections {
            get {
                return PersistedItems.OfType<CollectionsChildItem>();
            }
        }
    }
    
    public partial interface IEventConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class LiteralNodeBase : VariableNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ILiteralConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ComponentNodeBase : GenericInheritableNode, IClassTypeNode, IRequireConnectable {
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        [Section("Properties", SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<PropertiesChildItem> Properties {
            get {
                return PersistedItems.OfType<PropertiesChildItem>();
            }
        }
        
        [Section("Collections", SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CollectionsChildItem> Collections {
            get {
                return PersistedItems.OfType<CollectionsChildItem>();
            }
        }
    }
    
    public partial interface IComponentConnectable : IDiagramNodeItem, IConnectable {
    }

    public class AllFalseNodeBase : BoolExpressionNode
    {

        private string _ExpressionsInputSlotId;

        private Expressions _Expressions;

        public override bool AllowMultipleInputs
        {
            get
            {
                return true;
            }
        }

        public override bool AllowMultipleOutputs
        {
            get
            {
                return true;
            }
        }

        [Json.JsonProperty()]
        public virtual string ExpressionsInputSlotId
        {
            get
            {
                if (_ExpressionsInputSlotId == null)
                {
                    _ExpressionsInputSlotId = Guid.NewGuid().ToString();
                }
                return _ExpressionsInputSlotId;
            }
            set
            {
                _ExpressionsInputSlotId = value;
            }
        }

        [InputSlot("Expressions", true, SectionVisibility.Always, OrderIndex = 0, IsNewRow = true)]
        public virtual Expressions ExpressionsInputSlot
        {
            get
            {
                if (Repository == null)
                {
                    return null;
                }
                if (_Expressions != null)
                {
                    return _Expressions;
                }
                return _Expressions ?? (_Expressions = new Expressions() { Repository = Repository, Node = this, Identifier = ExpressionsInputSlotId });
            }
        }
    }

    public partial interface IAllFalseConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class IntNodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IIntConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class CollectionItemAddedNodeBase : CollectionModifiedHandlerNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ICollectionItemAddedConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ComponentDestroyedNodeBase : HandlerNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IComponentDestroyedConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class Vector2NodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IVector2Connectable : IDiagramNodeItem, IConnectable {
    }
    
    public class SequenceContainerNodeBase : SequenceItemNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ISequenceContainerConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class AllTrueNodeBase : BoolExpressionNode {
        
        private string _ExpressionsInputSlotId;
        
        private Expressions _Expressions;
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        [Json.JsonProperty()]
        public virtual string ExpressionsInputSlotId {
            get {
                if (_ExpressionsInputSlotId == null) {
                    _ExpressionsInputSlotId = Guid.NewGuid().ToString();
                }
                return _ExpressionsInputSlotId;
            }
            set {
                _ExpressionsInputSlotId = value;
            }
        }
        
        [InputSlot("Expressions", true, SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual Expressions ExpressionsInputSlot {
            get {
                if (Repository == null) {
                    return null;
                }
                if (_Expressions != null) {
                    return _Expressions;
                }
                return _Expressions ?? (_Expressions = new Expressions() { Repository = Repository, Node = this, Identifier = ExpressionsInputSlotId });
            }
        }
    }
    
    public partial interface IAllTrueConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class StartTimerNodeBase : GenericNode {
        
        private string _TimerInputSlotId;
        
        private Timer _Timer;
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        [Json.JsonProperty()]
        public virtual string TimerInputSlotId {
            get {
                if (_TimerInputSlotId == null) {
                    _TimerInputSlotId = Guid.NewGuid().ToString();
                }
                return _TimerInputSlotId;
            }
            set {
                _TimerInputSlotId = value;
            }
        }
        
        [InputSlot("Timer", false, SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual Timer TimerInputSlot {
            get {
                if (Repository == null) {
                    return null;
                }
                if (_Timer != null) {
                    return _Timer;
                }
                return _Timer ?? (_Timer = new Timer() { Repository = Repository, Node = this, Identifier = TimerInputSlotId });
            }
        }
    }
    
    public partial interface IStartTimerConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ConditionNodeBase : BoolExpressionNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IConditionConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ActionNodeBase : SequenceItemNode, IActionConnectable {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IActionConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class HandlerNodeBase : SequenceContainerNode, ISequenceItemConnectable {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IHandlerConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class SystemNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        [Section("Variables", SectionVisibility.WhenNodeIsFilter, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<VariablesChildItem> Variables {
            get {
                return PersistedItems.OfType<VariablesChildItem>();
            }
        }
    }
    
    public partial interface ISystemConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class EntityNodeBase : GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IEntityConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class ColorNodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IColorConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class EnumValueNodeBase : LiteralNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IEnumValueConnectable : IDiagramNodeItem, IConnectable {
    }
    
    public class SequenceItemNodeBase : GenericNode, ISequenceItemConnectable {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface ISequenceItemConnectable : IDiagramNodeItem, IConnectable {
    }
}
